### ISSUE TITLE
Error build in Arch Linux with OpenSSL v1.1.1

### ISSUE THREAD

**Issue by samtux** [t-rex-tileserver/t-rex#109]
I get the nex error compiling in Arch Linux x64 with OpenSSL version 1.1.1:

```
   Compiling http v0.1.13                                                                                                  
   Compiling crossbeam-deque v0.6.2                                                                                        
   Compiling mio-uds v0.6.7                                                                                                
   Compiling uuid v0.7.1                                                                                                   
   Compiling quote v0.6.10                                                                                                 
   Compiling url v1.7.2                                                                                                    
   Compiling geo-types v0.1.1                                                                                              
   Compiling streaming-stats v0.2.2                                                                                        
   Compiling openssl v0.9.24                                                                                               
error: failed to run custom build command for `openssl v0.9.24`                                                            
process didn't exit successfully: `/home/samtux/tmp/t-rex/target/debug/build/openssl-25e3859f3734ae66/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/samtux/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed 
```

```
error: failed to run custom build command for `openssl v0.9.24`                                                                                
process didn't exit successfully: `/home/samtux/tmp/t-rex/target/debug/build/openssl-25e3859f3734ae66/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/samtux/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
             at /build/rust/src/rustc-1.30.1-src/src/libstd/panicking.rs:411
   6: build_script_build::main
             at ./build.rs:16
   7: std::rt::lang_start::{{closure}}
             at /build/rust/src/rustc-1.30.1-src/src/libstd/rt.rs:74
   8: std::panicking::try::do_call
   9: __rust_maybe_catch_panic
  10: std::rt::lang_start_internal
  11: std::rt::lang_start
             at /build/rust/src/rustc-1.30.1-src/src/libstd/rt.rs:74
  12: main
  13: __libc_start_main
  14: _start

warning: build failed, waiting for other jobs to finish...
error: build failed                                                                                                                            
RUST_BACKTRACE=1 cargo build  22,68s user 0,62s system 194% cpu 11,994 total
```

**Comment by pka** [comment]
Seems to be an openssl version problem. https://github.com/rust-lang-nursery/rustup.rs/issues/1518 suggests updating packages with support for newer openssl versions.
Which version of t-rex are you compiling?

**Comment by pka** [comment]
A new dependency to `postgres-native-tls` updates to the newest `openssl` crate, which supports OpenSSL 1.1.1. Unfortunately `postgis` compilation fails at `postgres::tls::native_tls`. So `rust-postgis` needs an update first.

```diff
diff --git a/t-rex-core/Cargo.toml b/t-rex-core/Cargo.toml
index 94cf96c..b2d710a 100644
--- a/t-rex-core/Cargo.toml
+++ b/t-rex-core/Cargo.toml
@@ -18,6 +18,8 @@ r2d2 = "0.8"
 r2d2_postgres = "0.14"
 regex = "1"
 postgis = "0.6"
+postgres = "0.15"
+postgres-native-tls = "0.1"
 protobuf = "2.0"
 serde = "1.0"
 serde_derive = "1.0"
@@ -25,7 +27,3 @@ serde_json = "1.0"
 streaming-stats = "0.2.0"
 log = "0.4"
 flate2 = "1.0"
-
-[dependencies.postgres]
-version = "0.15"
-features = ["with-native-tls"]
```

**Comment by pka** [comment]
Can you try with latest master?
