### ISSUE TITLE
 ERROR IO error: invalid utf-8 sequence of 1 bytes from index 34

### ISSUE THREAD

**Issue by diouck** [t-rex-tileserver/t-rex#116]
Hello
After installation I have a problem and I can not serve the tiles. did you encounter this problem? I converted the database to utf-8 in vain. here is the error

```
2018-12-28 19:19:36.613 ERROR IO error: invalid utf-8 sequence of 1 bytes from index 34
thread 'arbiter:19aefcf2-470f-4769-9869-c90c0afa1bb3:actix-net-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Some("IO error: invalid utf-8 sequence of 1 bytes from index 34"))', libcore\result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'arbiter:1db4684e-3faa-4403-80b7-c6af8a3afe45:actix-net-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Some("IO error: invalid utf-8 sequence of 1 bytes from index 34"))', libcore\result.rs:1009:5
```

**Comment by pka** [comment]
I saw this error recently. The reason was a PostgreSQL connection error (refused login?).
An exception for this is a bug. You should find the cause by looking into the PostgreSQL log.

**Comment by diouck** [comment]
Thank you in fact it was beautiful and well a password problem.
On the other hand, there are other errors and the server runs in a vacuum in displaying the data. Where could it come from?
Thank you

`WARN Layer  my table converting field created_at to timestap to text `

**Comment by pka** [comment]
I'm afraid you hit another bug affecting Windows user. Which OS / version are you working on?

**Comment by diouck** [comment]
Ok I see the problem. I am windows 8. Now the viewer is displayed correctly but no map is displayed. in addition to that I have another mistake 
`INFO ATTENTION: ST_Shift_Longitude signature was deprecated in 2.2.0. Please use ST_ShiftLongitude`

And in linux ubuntu 18.4  i have this error

`Error reading configuration - configtrex.toml - redefinition of table `grid` for key `grid` at line 46
`

**Comment by pka** [comment]
The problem behind `ERROR Can not resume socket accept process` is a initialization problem of the asynchronous webserver built-in since t-rex 0.9.0. I had a workshop on Windows machines and on some machines the problem occorred almost never and on other machines the web server never started up. Changing the port sometimes helped, but I didn't find a way to solve the problem permanently. I will investigate this further.

Your messages on Linux are completely unrelated:
- The `ST_Shift_Longitude` is a warning which I currently ignore to stay compatilble with older PostGIS versions
- The  `www-browser: command not found` is just caused by a convinence function to open a browser windows automatically. Never saw before xdg-open not working on Ubuntu. Maybe setting `export BROWSER="google-chrome:gvfs-open:exo-open:kde-open"` or similar could solve this. Or you can add `--openbrowser false`.

The question why you don't see data with z > 0 is the remaining point. You can turn on debugging with `--loglevel debug` and then you will see the issued SQL queries. Testing some of them should give you a hint why the tiles are empty.

**Comment by diouck** [comment]
Hello and thank you. Yes in effect of disabled on the browser open with --openbrowser false.
Adding --lilevel debug for tiles> 0 here are the errors I currently have

 `2019-01-07 10:01:01.043 DEBUG avz_1_commerces/2/1/1 retrieving with Extent { minx: -10018754.17139463, miny: -10018754.17139463, maxx: -0.000000011175870895385742, maxy: -0.000000011175870895385742 }
2019-01-07 10:01:01.043 DEBUG avz_1_commerces/2/2/2 retrieving with Extent { minx: -0.000000011175870895385742, miny: -0.000000011175870895385742, maxx: 10018754.171394609, maxy: 10018754.171394609 }
2019-01-07 10:01:01.044 DEBUG avz_1_commerces/2/2/1 retrieving with Extent { minx: -0.000000011175870895385742, miny: -10018754.17139463, maxx: 10018754.171394609, maxy: -0.000000011175870895385742 }
2019-01-07 10:01:01.044 INFO GET /avz_1_commerces/2/1/1.pbf HTTP/1.1 200 354 1.000100ms 127.0.0.1:65398
2019-01-07 10:01:01.044 DEBUG executing query:
2019-01-07 10:01:01.044 DEBUG executing query:
2019-01-07 10:01:01.044 DEBUG executing query:
2019-01-07 10:01:01.045 DEBUG preparing query with name `s4`: SELECT ST_Transform(geom,3857) AS geom,"id_pole","id","post_id","libpole","enseigne","adresse","libnafolc","activite","svt","numcat","categorie","cat_auran" FROM avz_1_commerces WHERE geom && ST_Shift_Longitude(ST_Transform(ST_Buffer(ST_MakeEnvelope($1,$2,$3,$4,3857),10*$5::FLOAT8),4326))
2019-01-07 10:01:01.045 DEBUG preparing query with name `s4`: SELECT ST_Transform(geom,3857) AS geom,"id_pole","id","post_id","libpole","enseigne","adresse","libnafolc","activite","svt","numcat","categorie","cat_auran" FROM avz_1_commerces WHERE geom && ST_Shift_Longitude(ST_Transform(ST_Buffer(ST_MakeEnvelope($1,$2,$3,$4,3857),10*$5::FLOAT8),4326))
2019-01-07 10:01:01.046 DEBUG executing query: BEGIN
2019-01-07 10:01:01.047 DEBUG executing query: BEGIN
2019-01-07 10:01:01.047 DEBUG executing query: BEGIN
2019-01-07 10:01:01.048 DEBUG executing statement s4 with parameters: [-0.000000011175870895385742, -10018754.17139463, 10018754.171394609, -0.000000011175870895385742, 39135.75848201023]
2019-01-07 10:01:01.048 DEBUG executing statement s4 with parameters: [-10018754.17139463, -10018754.17139463, -0.000000011175870895385742, -0.000000011175870895385742, 39135.75848201023]
2019-01-07 10:01:01.048 DEBUG executing statement s4 with parameters: [-0.000000011175870895385742, -0.000000011175870895385742, 10018754.171394609, 10018754.171394609, 39135.75848201023]
2019-01-07 10:01:01.049 INFO ATTENTION: ST_Shift_Longitude signature was deprecated in 2.2.0. Please use ST_ShiftLongitude
2019-01-07 10:01:01.052 DEBUG Reading features in layer avz_1_commerces
2019-01-07 10:01:01.053 DEBUG executing query: ROLLBACK
2019-01-07 10:01:01.053 DEBUG avz_1_commerces/2/2/1 layer avz_1_commerces: 0 features
2019-01-07 10:01:01.053 DEBUG avz_1_commerces/2/2/2.pbf - Skipping empty tile
2019-01-07 10:01:01.053 INFO GET /avz_1_commerces/2/2/2.pbf HTTP/1.1 204 0 10.000600ms 127.0.0.1:65399
2019-01-07 10:01:01.056 INFO ATTENTION: ST_Shift_Longitude signature was deprecated in 2.2.0. Please use ST_ShiftLongitude
2019-01-07 10:01:01.058 INFO ATTENTION: ST_Shift_Longitude signature was deprecated in 2.2.0. Please use ST_ShiftLongitude
2019-01-07 10:01:01.060 DEBUG Reading features in layer avz_1_commerces
2019-01-07 10:01:01.061 DEBUG Reading features in layer avz_1_commerces
2019-01-07 10:01:01.061 DEBUG executing query: ROLLBACK
2019-01-07 10:01:01.061 DEBUG executing query: ROLLBACK
2019-01-07 10:01:01.061 DEBUG avz_1_commerces/2/1/1 layer avz_1_commerces: 0 features
2019-01-07 10:01:01.061 DEBUG avz_1_commerces/2/2/2 layer avz_1_commerces: 0 features
2019-01-07 10:01:01.061 DEBUG avz_1_commerces/2/1/2.pbf - Skipping empty tile
2019-01-07 10:01:01.061 DEBUG avz_1_commerces/2/2/1.pbf - Skipping empty tile
2019-01-07 10:01:01.061 INFO GET /avz_1_commerces/2/1/2.pbf HTTP/1.1 204 0 18.001100ms 127.0.0.1:65396
2019-01-07 10:01:01.062 INFO GET /avz_1_commerces/2/2/1.pbf HTTP/1.1 204 0 19.001100ms 127.0.0.1:65397
`

**Comment by pka** [comment]
I don't see any errors. The queries return 0 features within the given bounds.

**Comment by diouck** [comment]
Ok I solved my problem  on windows with type data and not MUlti and all walks to resent. Otherwise it has already been reported there are artifacts of tile with openlayer for the polygon
Thanks you
![t-rex-diouck](https://user-images.githubusercontent.com/3952114/50764438-e0e22700-1272-11e9-9979-818118302396.jpg)
