### ISSUE TITLE
Getting Started with OSM

### ISSUE THREAD

**Issue by boldtrn** [t-rex-tileserver/t-rex#118]
I was wondering if there is a getting started like tutorial to use t-rex with OSM?

If I understand the docs correctly, it is enough to setup a Postgis DB with e.g. `osm2pgsql` or `imposm`? Is there a config file that creates a well used vector tile schema like Mapbox, OpenMaptTiles Schema, or maybe plain OSM Schema?

For example I do have a .tm2source from OpenMapTiles. I think t-rex can't read tm2sources but I was wondering if the way to go would be to try and convert the tm2source?

**Comment by jimbok8** [comment]
I would also like this.
I have tried downloading a osm.pbf file and am struggling to get anything displayed.

**Comment by pka** [comment]
There is an example configuration for the osm2vectortiles schema, a predecessor of OpenMapTiles: https://github.com/t-rex-tileserver/t-rex/blob/master/examples/osm2vectortiles.toml

I would be happy to reference or include a tutorial using OSM data though.

**Comment by jimbok8** [comment]
This is what I have done so far:
Downloaded file "great-britain-latest.osm.pbf"
Downloaded "osm2vectortiles.toml" and edited it to change the data source:
_[[datasource]] 
path = "great-britain-latest.osm.pbf"_

I then run using this command:
_t_rex serve --config osm2vectortiles.toml_

This is the output:
E:\Programs\t-rex-v0.9.1>t_rex serve --config osm2vectortiles.toml
2019-02-22 09:15:16.501 INFO Reading configuration from 'osm2vectortiles.toml'
2019-02-22 09:15:16.508 INFO Starting 8 workers
2019-02-22 09:15:16.509 INFO Reading configuration from 'osm2vectortiles.toml'
2019-02-22 09:15:16.510 INFO Reading configuration from 'osm2vectortiles.toml'
2019-02-22 09:15:16.510 INFO Reading configuration from 'osm2vectortiles.toml'
2019-02-22 09:15:16.510 INFO Reading configuration from 'osm2vectortiles.toml'
2019-02-22 09:15:16.511 INFO Reading configuration from 'osm2vectortiles.toml'
2019-02-22 09:15:16.512 INFO Reading configuration from 'osm2vectortiles.toml'
2019-02-22 09:15:16.513 INFO Starting server on 127.0.0.1:6767
2019-02-22 09:15:16.513 INFO Reading configuration from 'osm2vectortiles.toml'
             xxxxxxxxx
        xxxxxxxxxxxxxxxxxxxxxxxx
      xxxxxxxxxxxxxxxxxxxxxxxxxxxx
     xxxxxxxxxxxxxxxxxxxxxxxxx xxxx
     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      x
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxx
xxxxxxxxxxxxxx                   xxxxxx
xxxxxxxxxxxx
xxxxxxxxxxx
xxxxxxxxxx
xxxxxxxxx
xxxxxxx
xxxxxx
xxxxxxx
2019-02-22 09:15:16.513 INFO Reading configuration from 'osm2vectortiles.toml'
thread 'arbiter:ee9d3853-d40d-42c2-9c73-f4400deb8480:actix-net-worker-7' panicke
d at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'arbiter:eba56d0f-44e3-44fe-83f4-58208dec6e44:actix-net-worker-5' panicke
d at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
thread 'arbiter:47c78358-2c70-4885-b812-6f0b5efa6918:actix-net-worker-3' panicke
d at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
thread 'arbiter:0f12829b-67ac-4045-aa6f-43153050c289:actix-net-worker-2' panicke
d at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
thread 'arbiter:fb916a5a-9956-4191-9119-bcf7d4a8f5b3:actix-net-worker-0' panicke
d at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
thread 'arbiter:5fe86767-9714-4e2b-833a-3549152cda3b:actix-net-worker-4' panicke
d at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
thread 'arbiter:070ab8a4-672b-4439-944d-a39038489ba2:actix-net-worker-1' panicke
d at 'thread 'called `Option::unwrap()` on a `None` valuearbiter:561042f3-93f9-4
2b7-aecd-505d948671ac:actix-net-worker-6', ' panicked at 'libcore\option.rscalle
d `Option::unwrap()` on a `None` value:', 345:libcore\option.rs21:
345:21

**Comment by pka** [comment]
In the meantime, there is a new example for the [OpenMapTiles](https://openmaptiles.org/docs/generate/generate-openmaptiles/) schema:  https://github.com/t-rex-tileserver/t-rex/blob/master/examples/openmaptiles.toml

**Comment by DanielEberhardt** [comment]
Is there any solution for this right now? I would also like to use t-rex to render osm data either from pbf file or from postgis database but I'm facing the same issues than @jimbok8 .

**Comment by kaushikray1** [comment]
I am having the exact similar issue. I used osm2pgsql to import the data to the database following the tutorial Switch2OSM so with openstreetmap-carto.lua and openstreetmap-carto.style
Now when I point the T-Rex server to this database and start the server I don't get any thing in the viewer all blank page. Can you please help.

Thank you
