### ISSUE TITLE
relation \"geometry_columns\" does not exist

### ISSUE THREAD

**Issue by musicformellons** [t-rex-tileserver/t-rex#253]
I am trying to have T-rex serve POINTS from a postgres database. 

When trying to generate tiles with:
```
./t_rex generate --config ~/osm.toml --loglevel debug
```

I get output like: 
```
Level 7: 857 / 16384 [========>---------------------------------------------------------------------------------------------------------------------------------------------------]  2021-07-23 10:06:06.541 DEBUG points/7/6/89 retrieving with Extent { minx: -18158991.935652755, miny: 7827151.696402051, maxx: -17845905.867796674, maxy: 8140237.764258131 }
2021-07-23 10:06:06.542 ERROR Layer 'points': db error: ERROR: function st_makeenvelope(unknown, unknown, unknown, unknown, integer) does not exist
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
2021-07-23 10:06:06.542 ERROR Layer 'points': db error: ERROR: function st_makeenvelope(unknown, unknown, unknown, unknown, integer) does not exist
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
2021-07-23 10:06:06.542 ERROR Layer 'points': db error: ERROR: function st_makeenvelope(unknown, unknown, unknown, unknown, integer) does not exist
[etcetera]
```

As I thought my config might be wrong, I try to generate a config but get:
```
 RUST_BACKTRACE=full ./t_rex genconfig --dbconn postgresql://postgres:secret@127.0.0.1:5432/t_rex
2021-08-18 16:51:48.428 INFO Detecting layers from geometry_columns
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P01), message: "relation \"geometry_columns\" does not exist", detail: None, hint: None, position: Some(Original(15)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(1376), routine: Some("parserOpenTable") }) }', t-rex-core/src/datasource/postgis_ds.rs:561:42
stack backtrace:
   0:        0x101b1a7a4 - std::backtrace_rs::backtrace::libunwind::trace::h20e18ecccca9aa2f
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x101b1a7a4 - std::backtrace_rs::backtrace::trace_unsynchronized::ha55ccb11ccfe3c25
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x101b1a7a4 - std::sys_common::backtrace::_print_fmt::h91ab27d175783056
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x101b1a7a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6db16a647ea8ef75
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x101b393f8 - core::fmt::write::h33ea04624f802921
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:        0x101b14828 - std::io::Write::write_fmt::hd387c43cb670231f
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:        0x101b1c4b4 - std::sys_common::backtrace::_print::h563761739011ae62
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x101b1c4b4 - std::sys_common::backtrace::print::h4b49287654569567
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x101b1c4b4 - std::panicking::default_hook::{{closure}}::hafe36fc92a4bd1da
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:        0x101b1bfec - std::panicking::default_hook::hf978639711baa931
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:        0x101b1ca4c - std::panicking::rust_panic_with_hook::hcafd722806bfc4bc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:        0x101b1c63c - std::panicking::begin_panic_handler::{{closure}}::h857e2d0c4fb1b7ef
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:        0x101b1ac34 - std::sys_common::backtrace::__rust_end_short_backtrace::hef54dc67870da455
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x101b1c5a4 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:        0x101b52f28 - core::panicking::panic_fmt::h70bba9f1fa3fca77
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:        0x101b52fc4 - core::result::unwrap_failed::h93f88410b7cbb383
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
  16:        0x1010d1a94 - core::result::Result<T,E>::unwrap::h88d9644df6e654fd
                               at /Users/pq/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
  17:        0x10111cbd0 - <t_rex_core::datasource::postgis_ds::PostgisDatasource as t_rex_core::datasource::datasource::DatasourceType>::detect_layers::hc702e5a398a4b593
                               at /Users/pq/Projects/t-rex/t-rex-core/src/datasource/postgis_ds.rs:561:21
  18:        0x1010877cc - <t_rex_service::datasources::Datasource as t_rex_core::datasource::datasource::DatasourceType>::detect_layers::h1d42c480dfc45e8d
                               at /Users/pq/Projects/t-rex/t-rex-service/src/datasources.rs:34:45
  19:        0x100c71714 - t_rex_webserver::runtime_config::service_from_args::h40f56539efef085d
                               at /Users/pq/Projects/t-rex/t-rex-webserver/src/runtime_config.rs:109:34
  20:        0x100c71f38 - t_rex_webserver::runtime_config::gen_config::hc2151685ca2c05c4
                               at /Users/pq/Projects/t-rex/t-rex-webserver/src/runtime_config.rs:157:23
  21:        0x100b3be24 - t_rex::main::h437a625748a20532
                               at /Users/pq/Projects/t-rex/src/main.rs:238:32
  22:        0x100b3e900 - core::ops::function::FnOnce::call_once::h8ac89c46d91f5b67
                               at /Users/pq/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  23:        0x100b3c864 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb578697782a27cfc
                               at /Users/pq/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  24:        0x100b44740 - std::rt::lang_start::{{closure}}::h0350e84f5af914b6
                               at /Users/pq/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:49:18
  25:        0x101b1ce7c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf054dac1d44effe3
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  26:        0x101b1ce7c - std::panicking::try::do_call::h71ec19ff440b61dc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  27:        0x101b1ce7c - std::panicking::try::h4e01023ed494c0ab
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  28:        0x101b1ce7c - std::panic::catch_unwind::h2d63c879c49e9192
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  29:        0x101b1ce7c - std::rt::lang_start_internal::h7e65a7643914896c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  30:        0x100b44718 - std::rt::lang_start::h07ec49c6f8e1944b
                               at /Users/pq/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:48:5
  31:        0x100b3c158 - _main
```

Looks like t-rex can not read my POINTS ('wkb_geometry') column or something? The columns show bytea as type for the points column.
<img width="387" alt="Screen Shot 2021-08-18 at 17 11 17" src="https://user-images.githubusercontent.com/10334123/129923996-44f14b43-e360-44d6-8fef-6de0241cada7.png">

**Comment by musicformellons** [comment]
Looks like a postgis installation issue.
