### ISSUE TITLE
[0.14.0] thread 'actix-web' panicked at 'not implemented', t-rex-core/src/datasource/datasource.rs:47:9

### ISSUE THREAD

**Issue by tobwen** [t-rex-tileserver/t-rex#260]
## tl;dr
`thread 'actix-web' panicked at 'not implemented', t-rex-core/src/datasource/datasource.rs:47:9`

## environment
build: https://github.com/t-rex-tileserver/t-rex/releases/download/v0.14.0/t-rex-v0.14.0-x86_64-linux-gnu.tar.gz
OS: Debian Bullseye, 64-bit

## RUST backtrace
<details>
<summary>open me</summary>

```
# RUST_BACKTRACE=full t_rex serve --config t-rex.toml
2021-09-18 02:09:43.510 INFO Reading configuration from 't-rex.toml'
thread 'actix-web' panicked at 'not implemented', t-rex-core/src/datasource/datasource.rs:47:9
stack backtrace:
   0:     0x55ea096077f0 - <unknown>
   1:     0x55ea0962d65c - <unknown>
   2:     0x55ea09600395 - <unknown>
   3:     0x55ea0960989b - <unknown>
   4:     0x55ea09609371 - <unknown>
   5:     0x55ea09609f64 - <unknown>
   6:     0x55ea09609a17 - <unknown>
   7:     0x55ea09607cec - <unknown>
   8:     0x55ea096099a9 - <unknown>
   9:     0x55ea08ec8751 - <unknown>
  10:     0x55ea08ec869d - <unknown>
  11:     0x55ea0922ce9a - <unknown>
  12:     0x55ea09170bde - <unknown>
  13:     0x55ea08f16039 - <unknown>
  14:     0x55ea08ef62c9 - <unknown>
  15:     0x55ea090e6861 - <unknown>
  16:     0x55ea090e706f - <unknown>
  17:     0x55ea0960fda7 - <unknown>
  18:     0x7f3fe7f0eea7 - start_thread
  19:     0x7f3fe7cf2def - clone
  20:                0x0 - <unknown>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', t-rex-webserver/src/server.rs:242:6
stack backtrace:
   0:     0x55ea096077f0 - <unknown>
   1:     0x55ea0962d65c - <unknown>
   2:     0x55ea09600395 - <unknown>
   3:     0x55ea0960989b - <unknown>
   4:     0x55ea09609371 - <unknown>
   5:     0x55ea09609f64 - <unknown>
   6:     0x55ea09609a47 - <unknown>
   7:     0x55ea09607cec - <unknown>
   8:     0x55ea096099a9 - <unknown>
   9:     0x55ea08ec8751 - <unknown>
  10:     0x55ea08ec8843 - <unknown>
  11:     0x55ea08fb0369 - <unknown>
  12:     0x55ea08f72950 - <unknown>
  13:     0x55ea08fcfa65 - <unknown>
  14:     0x55ea08f71005 - <unknown>
  15:     0x55ea08fbd6c9 - <unknown>
  16:     0x55ea08fa7138 - <unknown>
  17:     0x55ea08fbdd6a - <unknown>
  18:     0x55ea08eee7d5 - <unknown>
  19:     0x55ea08ee620f - <unknown>
  20:     0x55ea08ed0c43 - <unknown>
  21:     0x55ea08ee8389 - <unknown>
  22:     0x55ea0960a569 - <unknown>
  23:     0x55ea08ee71b2 - <unknown>
  24:     0x7f3fe7c1bd0a - __libc_start_main
  25:     0x55ea08ec8f2e - <unknown>
  26:                0x0 - <unknown>
Panic in Arbiter thread.
```

</details>

**Comment by tobwen** [comment]
Own build works, but has different dependencies: https://github.com/t-rex-tileserver/t-rex/issues/259#issuecomment-922148658

**Comment by pka** [comment]
The t-rex-v0.14.0-x86_64-linux-gnu tarball is built without GDAL support. I assume, you're getting his panic when accessing a GDAL datasource. So we should have a better error message here.
