### ISSUE TITLE
Crashing on database with multiple geometry type

### ISSUE THREAD

**Issue by RemiDesgrange** [t-rex-tileserver/t-rex#64]
hi, 

I have a big database with a lot of geometries, In some view dynamically created I have Multipolygon or geometry collection, I know this is not great :-) but this makes t-rex to crash :

``` 
docker run -p 6767:6767 -e RUST_BACKTRACE=1 sourcepole/t-rex serve --bind=0.0.0.0 --openbrowser=false --dbconn postgresql://user:password@example.com/myDB
2017-10-09 14:12:44.881 INFO Detecting layers from geometry_columns
2017-10-09 14:12:45.219 WARN Multiple geometry types in 'projet.v_ropt.st_multi':
2017-10-09 14:12:50.399 WARN Multiple geometry types in 'projet.v_implantation_projet.geom': MULTIPOLYGON, GEOMETRYCOLLECTION
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Db(DbError { severity: "ERREUR", parsed_severity: None, code: SyntaxError, message: "er
reur de syntaxe sur ou près de « - »", detail: None, hint: None, position: Some(Normal(88)), where_: None, schema: None, table: None, column: None, datatype: N
one, constraint: None, file: Some("scan.l"), line: Some(1052), routine: Some("scanner_yyerror") })', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: __libc_start_main
  14: <unknown>
```

Is there anyway to tell to t-rex to connect to a specific schema ?

(by the way this project is great !!)

**Comment by pka** [comment]
As a workaround you can configure a custom query:
```
[[tileset.layer.query]]
sql = """SELECT * FROM projet.v_implantation_projet WHERE geom && !bbox! AND GeometryType(geom)='MULTIPOLYGON'"""
```

If you could provide me the table / view content which causes the crash, I will look into it.

**Comment by RemiDesgrange** [comment]
This is complicated because this is a view (v_*) This view make a convexhull of some layer. I change my view to not output other things than mutlipolygone, but it's still crashing. 

I have some custom function in my db that have comments (--mycomments) and this comments it not necessary on the start of the line (it is indented), ex :
````plpgsql
CREATE FUNCTION foo() RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
   -- this is an indented comment, some tools don't like it apparently
  SELECT 1+1
END;
$$;
```
command:
```docker run -p 6767:6767 -e RUST_BACKTRACE=1 sourcepole/t-rex serve --bind=0.0.0.0 --openbrowser=false --dbconn postgresql://postgres:postgres@localhost/db
2017-10-10 08:29:58.364 INFO Detecting layers from geometry_columns
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Db(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SyntaxError, message: "syntax error at or near \"-\"", detail: None, hint: None, position: Some(Normal(88)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("scan.l"), line: Some(1086), routine: Some("scanner_yyerror") })', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: __libc_star
```
Tried with postgres 9.4, 9.6 and postgis 2.1,2.3 and 2.4, I think this is a drive issue (WDYT ?)

**Comment by pka** [comment]
Could you please try again with t-rex 0.9? It has some improvements regarding error handling (e.g. unkown types)

**Comment by RemiDesgrange** [comment]
yup:

``` bash
$ docker run sourcepole/t-rex --version
t_rex 0.9.0 (GDAL version 2.2.2)
$ cat config.toml
FROM sourcepole/t-rex
EXPOSE 6767
ENV RUST_BACKTRACE 1
WORKDIR /cache
COPY config.toml /conf/
CMD ["serve", "-c", "/conf/config.toml"]
```

config.toml
```toml
[service.mvt]
viewer = true

[[datasource]]
name = "testsource"
dbconn = "postgresql://postgres:postgres@myip/mydb"


[grid]
predefined = "web_mercator"

[[tileset]]
name = "test"

[[tileset.layer]]
name = "test_geometriecol"
datasource= "testsource"
srid= 2154
simplify = true
[[tileset.layer.query]]
sql = """
SELECT id, classedebi, st_makevalid(geom) from divers.observatoire_debit_2017
"""

[webserver]
bind = "0.0.0.0"
port = 6767
threads=4


[cache.file]
baseurl = "https://vector-tile.fibrea.net"
base = "/cache"
```


```
2018-07-31 07:24:35.804 INFO Reading configuration from '/conf/config.toml'
thread 'arbiter:e936ece4-ff8b-474e-b46d-2afe92f705e6:actor' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
thread 'arbiter:27535130-a3e3-4b69-bfc7-4038d39bc9df:actor' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: start_thread
  20: clone
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: start_thread
  20: clone
```

French bandwith observatory have a lot of invalid geometrie, `st_makevalid` will then generate geometrie collection of linestring/polygon.

**Comment by pka** [comment]
When using user defined queries, setting `geometry_field` is mandatory.

So please change the query to 
`SELECT id, classedebi, st_makevalid(geom) as geom ...`
and add a line
`geometry_field = "geom"

A better config check is definetively needed! As a beginning I've added a better panic message for this case.

**Comment by RemiDesgrange** [comment]
Ok it works !! I'm closing, great job
